# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_loaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamenuitem',
            name='img',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
